### ISSUE TITLE
Do you have a custom bt.feeds.CCXT python project?

### ISSUE THREAD

**Issue by johndpope** [j45p41/btrader#1]
File "bt_test.py", line 51, in <module>
    data = bt.feeds.CCXT(exchange=exchange,
AttributeError: module 'backtrader.feeds' has no attribute 'CCXT'

**python bt_test.py**
Traceback (most recent call last):
  File "bt_test.py", line 51, in <module>
    data = bt.feeds.CCXT(exchange=exchange,
AttributeError: module 'backtrader.feeds' has no attribute 'CCXT'
(tensorflow) ➜  btrader git:(master) pip install ccxt
Requirement already satisfied: ccxt in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages
Requirement already satisfied: yarl==1.1.0; python_version >= "3.5.3" in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from ccxt)
Requirement already satisfied: cchardet==2.1.1; python_version >= "3.5.3" in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from ccxt)
Requirement already satisfied: certifi==2018.1.18 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from ccxt)
Requirement already satisfied: setuptools==38.5.1 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from ccxt)
Requirement already satisfied: requests==2.18.4 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from ccxt)
Requirement already satisfied: aiohttp==3.0.1; python_version >= "3.5.3" in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from ccxt)
Requirement already satisfied: aiodns==1.1.1; python_version >= "3.5.3" in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from ccxt)
Requirement already satisfied: idna>=2.0 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from yarl==1.1.0; python_version >= "3.5.3"->ccxt)
Requirement already satisfied: multidict>=4.0 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from yarl==1.1.0; python_version >= "3.5.3"->ccxt)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from requests==2.18.4->ccxt)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from requests==2.18.4->ccxt)
Requirement already satisfied: attrs>=17.4.0 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from aiohttp==3.0.1; python_version >= "3.5.3"->ccxt)
Requirement already satisfied: idna-ssl>=1.0 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from aiohttp==3.0.1; python_version >= "3.5.3"->ccxt)
Requirement already satisfied: async-timeout<3.0,>=1.2 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from aiohttp==3.0.1; python_version >= "3.5.3"->ccxt)
Requirement already satisfied: pycares>=1.0.0 in /Users/johndpope/miniconda3/envs/tensorflow/lib/python3.6/site-packages (from aiodns==1.1.1; python_version >= "3.5.3"->ccxt)

**Comment by johndpope** [comment]
found it. 
https://github.com/Dave-Vallance/temp/tree/b097626a79891f01c120d80964782b2a1e5b21f5/backtrader/feeds
